version: '3.5'
services:
  consulserver:
    container_name: ws_consul_server
    image: 'consul:1.13.2'
    volumes:
      - 'consulserver_data:/consul/data'
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client='0.0.0.0'
  consulclient:
    container_name: ws_consul_client
    image: 'consul:1.13.2'
    volumes:
      - 'consulclient_data:/consul/data'
    command: consul agent -node=client-1 -join=consulserver -data-dir=/consul/data -config-dir=/consul/config -enable-local-script-checks -client='0.0.0.0'
    depends_on:
      - consulserver

  service:
    build: ./service
    container_name: ws_service
    ports:
      - '9080:8080'
    depends_on:
      - consulclient
      - rabbitmq
  
  apimmongodb:
    image: 'mongo:3.6'
    container_name: ws_apim_mongodb
    volumes:
      - 'apim_datamongo:/data/db'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.7.0'
    container_name: ws_elasticsearch
    volumes:
      - 'apim_dataelasticsearch:/usr/share/elasticsearch/data'
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
  apimgateway:
    image: 'graviteeio/apim-gateway:3.18.10'
    container_name: ws_apim_gateway
    depends_on:
      - apimmongodb
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://apimmongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://apimmongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - 'gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200'
      - gravitee_http_websocket_enabled=true
      - gravitee_http_websocket_subProtocols=v10.stomp, v11.stomp, v12.stomp
      - GIO_MIN_MEM=512m
      - GIO_MAX_MEM=1024m
  apimmanagement:
    image: 'graviteeio/apim-management-api:3.18.10'
    container_name: ws_apim_management_api
    links:
      - apimmongodb
      - elasticsearch
    depends_on:
      - apimmongodb
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://apimmongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - 'gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200'
      - GIO_MIN_MEM=512m
      - GIO_MAX_MEM=1024m
  apimmanagementui:
    image: 'graviteeio/apim-management-ui:3.18.10'
    container_name: ws_apim_management_ui
    depends_on:
      - apimmanagement
    environment:
      - MGMT_API_URL=http://localhost/apim/management/management/organizations/DEFAULT/environments/DEFAULT/
  apimportalui:
    image: 'graviteeio/apim-portal-ui:3.18.10'
    container_name: ws_apim_portal_ui
    depends_on:
      - apimmanagement
    environment:
      - PORTAL_API_URL=http://localhost/apim/management/portal/environments/DEFAULT
  
  nginx:
    image: 'nginx:1.23-alpine'
    container_name: ws_nginx
    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    depends_on:
      - apimgateway
      - apimmanagement
      - apimmanagementui
      - apimportalui

  rabbitmq:
    build: ./rabbitmq
    hostname: rabbitmq 
    container_name: ws_rabbitmq
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
      - "./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      
volumes:
  consulserver_data:
    driver: local
  consulclient_data:
    driver: local
  apim_dataelasticsearch:
    driver: local
  apim_datamongo:
    driver: local
  rabbitmq_data:
    driver: local
